// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPp7v0jLUE8UjCw49PdrvkbrawPbVWZa8',
    appId: '1:47779725558:web:ad2c1399387249a68c2cd7',
    messagingSenderId: '47779725558',
    projectId: 'college-bus-management-s-a8b60',
    authDomain: 'college-bus-management-s-a8b60.firebaseapp.com',
    databaseURL: 'https://college-bus-management-s-a8b60-default-rtdb.firebaseio.com',
    storageBucket: 'college-bus-management-s-a8b60.appspot.com',
    measurementId: 'G-TNRCYDXKFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZcsanQcSTq6k_wnmEcErURnKse79UYE',
    appId: '1:47779725558:android:995ff333693adaab8c2cd7',
    messagingSenderId: '47779725558',
    projectId: 'college-bus-management-s-a8b60',
    databaseURL: 'https://college-bus-management-s-a8b60-default-rtdb.firebaseio.com',
    storageBucket: 'college-bus-management-s-a8b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPo_Oe0kwNpYTA8U8iB-zKRdc_km7k3cw',
    appId: '1:47779725558:ios:d0675c6cb28c662a8c2cd7',
    messagingSenderId: '47779725558',
    projectId: 'college-bus-management-s-a8b60',
    databaseURL: 'https://college-bus-management-s-a8b60-default-rtdb.firebaseio.com',
    storageBucket: 'college-bus-management-s-a8b60.appspot.com',
    iosClientId: '47779725558-qh0pd20hrpevn358mni0pc329p52p1r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbms',
  );
}
